# mysql + redis latest
version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
    # get from .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
